/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;
import javax.swing.*;
/**
 *
 * @author Melvin
 */
public class Calcular extends javax.swing.JFrame {
int v1=0,v2=0,resultado;
    /**
     * Creates new form Calcular
     */
    public Calcular() {
        initComponents();
    }
    
    public void refrescar(){
        txtv1.setText("");
        txtv2.setText("");
        txtresultado.setText("");
        
        txtv1.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void suma(){
        v1=Integer.parseInt(txtv1.getText());
        v2=Integer.parseInt(txtv2.getText());
        
        resultado=v1+v2;
        
        txtresultado.setText(""+resultado);
        
    }
    
       public void resta(){
        v1=Integer.parseInt(txtv1.getText());
        v2=Integer.parseInt(txtv2.getText());
        
        resultado=v1-v2;
        
        txtresultado.setText(""+resultado);
        
    }
       
       public void multiplica(){
        v1=Integer.parseInt(txtv1.getText());
        v2=Integer.parseInt(txtv2.getText());
        
       resultado=v1*v2;
        
        txtresultado.setText(""+resultado);
        
    }
       
       public void division(){
        v1=Integer.parseInt(txtv1.getText());
        v2=Integer.parseInt(txtv2.getText());
        
        if(v1>0 && v2>0 ){
       resultado=v1/v2;
        
        txtresultado.setText(""+resultado);     
        }
       
        else{
            if(v2==0 || v1==0){
                txtresultado.setText("Error");
            }
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtv1 = new javax.swing.JTextField();
        txtv2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtresultado = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btsuma = new javax.swing.JButton();
        btresta = new javax.swing.JButton();
        btmultiplica = new javax.swing.JButton();
        btdividir = new javax.swing.JButton();
        btrefrescar = new javax.swing.JButton();
        btoff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor 1");

        jLabel2.setText("Valor 2");

        jLabel3.setText("Resultado");

        jToolBar1.setRollover(true);

        btsuma.setText("+");
        btsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsumaActionPerformed(evt);
            }
        });
        jToolBar1.add(btsuma);

        btresta.setText("-");
        btresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrestaActionPerformed(evt);
            }
        });
        jToolBar1.add(btresta);

        btmultiplica.setText("X");
        btmultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmultiplicaActionPerformed(evt);
            }
        });
        jToolBar1.add(btmultiplica);

        btdividir.setText("/");
        btdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdividirActionPerformed(evt);
            }
        });
        jToolBar1.add(btdividir);

        btrefrescar.setText("AC");
        btrefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrefrescarActionPerformed(evt);
            }
        });
        jToolBar1.add(btrefrescar);

        btoff.setText("Off");
        btoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoffActionPerformed(evt);
            }
        });
        jToolBar1.add(btoff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtv2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtv1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrefrescarActionPerformed
        // TODO add your handling code here:
        refrescar();
        
        
    }//GEN-LAST:event_btrefrescarActionPerformed

    private void btoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoffActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btoffActionPerformed

    private void btsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsumaActionPerformed
        // TODO add your handling code here:
        suma();
    }//GEN-LAST:event_btsumaActionPerformed

    private void btrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrestaActionPerformed
        // TODO add your handling code here:
        resta();
    }//GEN-LAST:event_btrestaActionPerformed

    private void btmultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmultiplicaActionPerformed
        // TODO add your handling code here:
        multiplica();
        
    }//GEN-LAST:event_btmultiplicaActionPerformed

    private void btdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdividirActionPerformed
        // TODO add your handling code here:
        division();
    }//GEN-LAST:event_btdividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdividir;
    private javax.swing.JButton btmultiplica;
    private javax.swing.JButton btoff;
    private javax.swing.JButton btrefrescar;
    private javax.swing.JButton btresta;
    private javax.swing.JButton btsuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtresultado;
    private javax.swing.JTextField txtv1;
    private javax.swing.JTextField txtv2;
    // End of variables declaration//GEN-END:variables
}
